# Numpy

In [3]:
a = [1,2,3,4]
b = [2,3,4,5]
a


[1, 2, 3, 4]

In [4]:
b

[2, 3, 4, 5]

In [6]:
ab = []

for i in range (0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [9]:
a*b

array([ 2,  6, 12, 20])

# NumpPy Array'ı oluşturmak

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([3.14,4,2,13]) # numpy sabit tip (one type) sağlar

array([ 3.14,  4.  ,  2.  , 13.  ])

In [10]:
np.array([3.14,4,2,13], dtype="int") # type değiştirme

array([ 3,  4,  2, 13])

# Sıfırdan array oluşturma işlemleri

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [18]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [19]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
np.random.normal(10,4,(3,4))

array([[ 7.19821009,  9.06639184,  9.79588856,  6.97059647],
       [11.7862029 ,  9.91497449, 11.80731005,  9.58377578],
       [ 7.77126069, 10.43516481, 12.67569625, 14.18900607]])

In [21]:
np.random.randint(0,10,(3,3))

array([[9, 2, 3],
       [7, 3, 6],
       [6, 5, 0]])

#Özellikler
* **ndim** : boyut sayısı
* **shape** : boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri bilgisi

In [23]:
np.random.randint(10,size = 10)

array([1, 8, 7, 1, 4, 2, 1, 9, 8, 8])

In [24]:
a=np.random.randint(10,size = 10)

In [26]:
a.ndim

1

In [27]:
a.shape

(10,)

In [28]:
a.size

10

In [29]:
a.dtype

dtype('int32')

In [30]:
b=np.random.randint(10,size = (3,5))

In [31]:
b

array([[2, 4, 7, 2, 0],
       [9, 1, 5, 5, 5],
       [1, 2, 2, 6, 1]])

In [32]:
b.ndim

2

In [33]:
b.shape

(3, 5)

In [34]:
b.size

15

In [35]:
b.dtype

dtype('int32')

# Yeniden şekillendirme (RESHAPING)

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,10).reshape((3,3)) # 3x3 matrix'e çevirdik

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a=np.arange(1,10)

In [40]:
a.ndim

1

In [42]:
b=a.reshape((1,9)) # boyut sayısını arttırdık

In [43]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [45]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [46]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [47]:
z = np.array([7,8,9])

In [48]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# İki boyutta

In [50]:
a = np.array([[1,2,3],
              [4,5,6]])

In [51]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([a,a], axis = 0) # axis 0 ise satır bazında, 1 ise sütün bazında birleştir

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Array ayırma (split)

In [57]:
x = np.array([1,2,3,99,99,3,2,1])

In [58]:
np.split(x,[3,5]) # 3'e kadar ve  5'e kadar böldü

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [59]:
a,b,c = np.split(x,[3,5]) # 3 çıktıyı a b ve c'ye atadı

In [60]:
a

array([1, 2, 3])

In [61]:
b

array([99, 99])

In [62]:
c

array([3, 2, 1])

In [63]:
# İki boyutlu ayırma

In [66]:
m = np.arange(16).reshape(4,4)

In [67]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [70]:
ust,alt = np.vsplit(m,[2])

In [71]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.hsplit(m,[2]) # yatay bölme

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
sag,sol = np.hsplit(m,[2]) 

In [77]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [78]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama

In [80]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [81]:
np.sort(v) # küçükten büyüğe sıralar ve v'nin yapısını değiştirmez

array([1, 2, 3, 4, 5])

In [82]:
v.sort() # bu da sıralama yapar ama v artık sıralıdır yapısı değişmiştir

In [83]:
v

array([1, 2, 3, 4, 5])

In [85]:
# Çok boyuttan sıralama

In [86]:
m =np.random.normal(20,5,(3,3))

In [87]:
m

array([[12.36515369, 13.82969476, 20.90651126],
       [23.48344397, 18.83804978, 25.47086937],
       [20.61983413, 21.8068771 , 23.1083181 ]])

In [88]:
np.sort(m,axis=1) # satır sıralaması

array([[12.36515369, 13.82969476, 20.90651126],
       [18.83804978, 23.48344397, 25.47086937],
       [20.61983413, 21.8068771 , 23.1083181 ]])

In [89]:
np.sort(m,axis=0) # sütün sıralaması

array([[12.36515369, 13.82969476, 20.90651126],
       [20.61983413, 18.83804978, 23.1083181 ],
       [23.48344397, 21.8068771 , 25.47086937]])

# İndex ile elemana erişme

In [91]:
a = np.random.randint(10,size=10)
a

array([4, 1, 5, 5, 7, 4, 5, 3, 8, 2])

In [92]:
a[0]

4

In [93]:
a[-1]

2

In [94]:
a[0] = 100

In [95]:
a

array([100,   1,   5,   5,   7,   4,   5,   3,   8,   2])

In [96]:
m = np.random.randint(10,size=(3,5))
m

array([[5, 1, 3, 5, 6],
       [2, 7, 6, 7, 9],
       [3, 1, 9, 2, 9]])

In [97]:
m[0,0]

5

In [98]:
m[1,3]

7

In [99]:
m[1,3] = 99

In [100]:
m

array([[ 5,  1,  3,  5,  6],
       [ 2,  7,  6, 99,  9],
       [ 3,  1,  9,  2,  9]])

In [101]:
m[1,4] = 2.1 # ondalık kısmı almaz çünkü tek tipli olur np arrayler

In [102]:
m

array([[ 5,  1,  3,  5,  6],
       [ 2,  7,  6, 99,  2],
       [ 3,  1,  9,  2,  9]])

# Slicing ile Elemanlara erişmek (Alt kümeye erişmek)

In [103]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [104]:
a[0:3]

array([20, 21, 22])

In [105]:
a[:3]

array([20, 21, 22])

In [108]:
a[1::2] # 1. indexten 2şer git

array([21, 23, 25, 27, 29])

In [109]:
# İki boyutlu işlem

In [110]:
m = np.random.randint(10,size=(5,5))

In [111]:
m

array([[2, 4, 0, 8, 3],
       [1, 4, 5, 3, 8],
       [5, 4, 4, 1, 7],
       [2, 8, 0, 3, 0],
       [0, 3, 9, 1, 5]])

In [112]:
m[:,0]

array([2, 1, 5, 2, 0])

In [113]:
m[:,1]

array([4, 4, 4, 8, 3])

In [114]:
m[0,:]

array([2, 4, 0, 8, 3])

In [115]:
m[1,:]

array([1, 4, 5, 3, 8])

In [117]:
m[0:2,0:3] # 0dan 2'ye kadar satır al 0dan 3'e kadar sütün al

array([[2, 4, 0],
       [1, 4, 5]])

In [118]:
m[:,:2]

array([[2, 4],
       [1, 4],
       [5, 4],
       [2, 8],
       [0, 3]])

# Alt Küme Üzerinde İşlem Yapmak

In [119]:
a = np.random.randint(10,size = (5,5))
a

array([[1, 0, 3, 5, 0],
       [8, 7, 1, 2, 6],
       [6, 0, 7, 4, 4],
       [8, 4, 0, 7, 8],
       [9, 0, 3, 1, 9]])

In [120]:
alt_a = a[0:3,0:2]
alt_a

array([[1, 0],
       [8, 7],
       [6, 0]])

In [121]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888
alt_a

array([[9999,    0],
       [   8, 8888],
       [   6,    0]])

In [123]:
a # ana arrayı değiştiriyor

array([[9999,    0,    3,    5,    0],
       [   8, 8888,    1,    2,    6],
       [   6,    0,    7,    4,    4],
       [   8,    4,    0,    7,    8],
       [   9,    0,    3,    1,    9]])

In [124]:
# ana arrayı değiştirmemek için

In [126]:
m = np.random.randint(10,size=(5,5))
m

array([[9, 1, 6, 1, 3],
       [6, 7, 4, 0, 4],
       [4, 0, 8, 7, 5],
       [6, 3, 5, 3, 4],
       [5, 5, 8, 8, 6]])

In [127]:
alt_b = m[0:3,0:3].copy()
alt_b

array([[9, 1, 6],
       [6, 7, 4],
       [4, 0, 8]])

In [128]:
alt_b[0,0] = 9999
alt_b

array([[9999,    1,    6],
       [   6,    7,    4],
       [   4,    0,    8]])

In [129]:
m # değişme olmadı

array([[9, 1, 6, 1, 3],
       [6, 7, 4, 0, 4],
       [4, 0, 8, 7, 5],
       [6, 3, 5, 3, 4],
       [5, 5, 8, 8, 6]])

# Fancy Index ile Elemanlara erişmek

In [130]:
v = np.arange(0,30,3)

In [131]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [132]:
v[1]

3

In [133]:
v[3]

9

In [134]:
v[5]

15

In [135]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [136]:
al_getir = [1,3,5]

In [137]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [138]:
v[al_getir]

array([ 3,  9, 15])

In [139]:
# İki boyutta

In [140]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [142]:
m[satir,sutun]

array([1, 5])

In [143]:
# Basit İndex ile Fancy İndex

In [144]:
m[0,[1,2]]

array([1, 2])

In [145]:
m[0:,[1,2]] #slice

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu eleman işlemleri

In [147]:
 v = np.array([1,2,3,4,5])

In [148]:
v>5

array([False, False, False, False, False])

In [149]:
v<3

array([ True,  True, False, False, False])

In [150]:
v[v<3]

array([1, 2])

In [151]:
v[v>3]

array([4, 5])

# Matematiksel İşlemler

In [ ]:
v = np.array([1,2,3,4,5])

In [152]:
v*2

array([ 2,  4,  6,  8, 10])

In [154]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [155]:
v - 1

array([0, 1, 2, 3, 4])

In [156]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [157]:
# ufunc

In [158]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [159]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [160]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [161]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [162]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [163]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [164]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [165]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [166]:
np.absolute(np.array([-3]))

array([3])

In [167]:
np.sin(360)

0.9589157234143065

In [168]:
np.cos(180)

-0.5984600690578581

In [169]:
np.sin(0)

0.0

In [170]:
v = np.array([1,2,3])

In [171]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [172]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [173]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\asus\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\asus\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

# İki bilinmeyenli Denklem çözümü

5*x0+x1 = 12

x0+3*x1 = 10

In [175]:
a = np.array([[5,1],[1,3]])

In [176]:
b = np.array([12,10])

In [177]:
x = np.linalg.solve(a,b)

In [178]:
x

array([1.85714286, 2.71428571])